-- Ядро hub.db (§4 spec + inbox из карточки H01).
CREATE TABLE IF NOT EXISTS task (
  id TEXT PRIMARY KEY,
  project TEXT NOT NULL DEFAULT '',
  card_path TEXT NOT NULL DEFAULT '',
  card_hash TEXT NOT NULL DEFAULT '',
  level TEXT NOT NULL DEFAULT '',
  branch TEXT NOT NULL DEFAULT '',
  worktree TEXT NOT NULL DEFAULT '',
  base_sha TEXT NOT NULL DEFAULT '',
  stage TEXT NOT NULL DEFAULT 'queued',
  round INTEGER NOT NULL DEFAULT 0,
  executor TEXT NOT NULL DEFAULT '',
  reviewers_json TEXT NOT NULL DEFAULT '[]',
  stage_reason TEXT NOT NULL DEFAULT '',
  budget_go REAL NOT NULL DEFAULT 0.5,
  budget_usd REAL NOT NULL DEFAULT 0.0,
  created_at INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0,
  merged_sha TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS session (
  external_id TEXT PRIMARY KEY,
  tool TEXT NOT NULL DEFAULT 'opencode',
  task_id TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'executor',
  round INTEGER NOT NULL DEFAULT 0,
  model TEXT NOT NULL DEFAULT '',
  started_at INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_session_task ON session(task_id);
CREATE TABLE IF NOT EXISTS event (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER NOT NULL DEFAULT 0,
  task_id TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT '',
  payload_json TEXT NOT NULL DEFAULT '{}',
  seen_claude INTEGER NOT NULL DEFAULT 0,
  sent_tg INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_event_task ON event(task_id, id);
CREATE TABLE IF NOT EXISTS question (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id TEXT NOT NULL DEFAULT '',
  asked_by TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL DEFAULT '',
  options_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'open',
  answer TEXT NOT NULL DEFAULT '',
  answered_via TEXT NOT NULL DEFAULT '',
  ts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_question_task ON question(task_id, id);
CREATE TABLE IF NOT EXISTS inbox (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER NOT NULL DEFAULT 0,
  text TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT '',
  seen_claude INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS budget (
  scope TEXT NOT NULL,
  key TEXT NOT NULL,
  go_limit REAL NOT NULL DEFAULT 0.0,
  usd_limit REAL NOT NULL DEFAULT 0.0,
  hard INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (scope, key)
);
